name: circle
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  uuid: ^3.0.5
  intl: ^0.17.0
  http: ^0.13.4
  share: ^2.0.4
  formz: ^0.4.1
  rxdart: ^0.27.3
  equatable: ^2.0.3
  geolocator: ^7.7.1
  screenshot: ^1.2.3
  photo_view: ^0.13.0
  timer_button: ^2.0.0
  flutter_html: ^2.1.5
  flutter_bloc: ^7.3.3
  google_fonts: ^2.1.0
  url_launcher: ^6.0.15
  image_picker: ^0.8.4+4
  path_provider: ^2.0.7
  image_cropper: ^1.4.1
  dropdown_search: ^2.0.1
  pin_code_fields: ^7.3.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.4
  cupertino_icons: ^1.0.4
  flutter_spinkit: ^5.1.0
  device_info_plus: ^3.1.1
  firebase_storage: ^10.1.0
  permission_handler: ^8.3.0
  firebase_messaging: ^11.1.0
  proste_bezier_curve: ^2.0.2
  country_code_picker: ^2.0.2
  google_maps_flutter: ^2.1.1
  font_awesome_flutter: ^9.2.0
  double_back_to_close: ^2.0.0
  youtube_player_iframe: ^2.2.2
  html: ^0.15.0
  bubble: ^1.2.1
  file_picker: ^4.2.3
  linkfy_text: ^1.1.5
  package_info: ^2.0.2
  open_appstore: ^1.0.2
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  google_sign_in: ^5.2.1
  flutter_pdfview: ^1.2.1
  firebase_database: ^8.1.0
  sign_in_with_apple: ^3.3.0
  very_good_analysis: ^2.4.0
  flutter_cache_manager: ^3.1.3
  cached_network_image: ^3.1.0+1
  excel: ^2.0.0-null-safety-3

  form_inputs:
    path: packages/form_inputs

  flutter_chat:
    path: packages/flutter_chat

  force_update:
    path: packages/force_update

  geocoder:
    path: packages/flutter_geocoder

  whatsapp_share:
    path: packages/whatsapp_share

  easy_contact_picker:
    path: packages/easy_contact_picker

  authentication_repository:
    path: packages/authentication_repository

dependency_overrides:

  webview_flutter: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/json/
    - assets/home/
    - assets/empty/
    - assets/offer/
    - assets/slider/
    - assets/default/